name: Test
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run passing script
        run: |
          chmod +x ./good.sh && ./good.sh
      - name: Run failing script
        run: |
          chmod +x ./bad.sh && ./bad.sh
